# generated by datamodel-codegen:
#   filename:  sample.json
#   timestamp: 2020-09-16T13:28:39+00:00


from typing import List, Optional

from pydantic import BaseModel, Field


class PublishedDate(BaseModel):
    _date: str = Field(..., alias='$date')


class Book(BaseModel):
    _id: Optional[int]
    title: Optional[str]
    isbn: Optional[str]
    page_count: Optional[int] = Field(..., alias='pageCount')
    published_date: Optional[PublishedDate] = Field(..., alias='publishedDate')
    thumbnail_url: Optional[str] = Field(..., alias='thumbnailUrl')
    short_description: Optional[str] = Field(..., alias='shortDescription')
    long_description: Optional[str] = Field(..., alias='longDescription')
    status: Optional[str]
    authors: Optional[List[str]]
    categories: Optional[List[str]]
