apiVersion: apps/v1
kind: Deployment
metadata:
  name: cwdb-api
  labels:
    app: cwdb-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cwdb-api
  template:
    metadata:
      labels:
        app: cwdb-api
    spec:
      containers:
        - name: cwdb-api
          image: chillshyld/cwdb
          ports:
            - containerPort: 8000
