# name: build

# on:
#   push:
#     branches:
#       - master
#     paths:
#       - "app/**"

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Tag
#         id: tag
#         run: echo "::set-output name=SHA7::$(echo ${GITHUB_SHA:0:7})"

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v1

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Login to DockerHub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build and push
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           file: ./docker/Dockerfile
#           push: true
#           build-args: MONGO_URI=${{secrets.MONGO_URI}}
#           tags: |
#             aofdev/complete-web-development-bootcamp-api:latest
#             aofdev/complete-web-development-bootcamp-api:${{ steps.tag.outputs.SHA7 }}
