# name: Deploy-heroku

# on:
#   push:
#     branches:
#       - master
#     paths:
#       - "app/**"

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: akhileshns/heroku-deploy@v3.4.6
#         with:
#           heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#           heroku_app_name: "cwdb-api"
#           heroku_email: "aof.dev@gmail.com"
#           usedocker: true
#           docker_build_args: MONGO_URI=${{secrets.MONGO_URI}}
