name: Deploy-Kubernetes

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run some test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start app
        run: docker-compose up -d

      - name: Restore data
        run: |
          docker cp ./seed/books.json complete-web-development-bootcamp-mongo:/tmp/books.json
          docker exec complete-web-development-bootcamp-mongo mongoimport --uri "mongodb://cwdb101:!cwdb101!@complete-web-development-bootcamp-mongo:27017/bootcamp?authSource=admin&authMechanism=SCRAM-SHA-1" -c books --drop --file /tmp/books.json

      - name: Integration test
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: postman/Complete-Web-Developer-Bootcamp-API.postman_collection.json
          environment: postman/Bootcamp-Local.postman_environment.json
          reporters: cli

  build:
    name: Build and push image
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker-temp/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: chillshyld/cwdb:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
